# Generated by Django 6.0.6 on 2026-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yjs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='compressed_timeline',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
