# Generated by Django 6.0.5 on 2026-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('PRACTICE', 'Practice'), ('MOCK', 'Mock')], default='PRACTICE'),
        ),
    ]
