# Generated by Django 6.0.5 on 2026-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='mode',
            new_name='testMode',
        ),
    ]
