# Generated by Django 6.0.6 on 2026-06-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_rename_output_types_problem_output_type'),
        ('rooms', '0003_rename_mode_room_testmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.problem'),
        ),
    ]
