# Generated by Django 6.0.5 on 2026-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
