# Generated by Django 6.0.5 on 2026-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
