# Generated by Django 6.0.6 on 2026-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order_matters',
            field=models.BooleanField(default=False),
        ),
    ]
