# Generated by Django 6.0.6 on 2026-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_order_matters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='order_matters',
            field=models.BooleanField(default=True),
        ),
    ]
