# Generated by Django 6.0.6 on 2026-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_order_matters'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_types',
            field=models.JSONField(default=dict),
        ),
    ]
