# Generated by Django 6.0.6 on 2026-06-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_input_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='output_types',
            field=models.JSONField(default=dict),
        ),
    ]
