# Generated by Django 6.0.6 on 2026-06-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_output_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='output_types',
            new_name='output_type',
        ),
    ]
