name: codearena

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - yjs

  backend:
    ports:
      - "8000:8000"
    build:
      context: ./backend/
    volumes:
      - type: bind
        source: ./backend/
        target: /app/
    depends_on:
      - db
      - redis
    env_file:
      - db.env
      - backend.env

  db:
    image: postgres:18.4
    env_file: "db.env"
    volumes:
      - pgdata:/var/lib/postgresql/
    
  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  
  yjs:
    image: node:24-slim
    working_dir: /app
    command: sh -c "npm install @y/websocket-server y-websocket && npx y-websocket"
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - HOST=0.0.0.0

volumes:
  pgdata:
  redis_data:
