# Generated by Django 6.0.6 on 2026-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='actual_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='execution_time',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
