# Generated by Django 6.0.6 on 2026-06-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_submission_actual_output_submission_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='actual_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
